import { IProduct } from '../../types'

export const products: IProduct[] = [
	{
		name: 'Telefon',
		code: 'T123',
		remaining: 50,
		price: 1200,
		rating: 4.5,
		reviews: 120,
		category: 'Elektronika',
	},
	{
		name: 'Konditsioner',
		code: 'K234',
		remaining: 30,
		price: 1500,
		rating: 4.8,
		reviews: 200,
		category: 'Maishiy texnika',
	},
	{
		name: 'Futbolka',
		code: 'F345',
		remaining: 100,
		price: 30,
		rating: 4.2,
		reviews: 50,
		category: 'Kiyim-kechak',
	},
	{
		name: 'Sport kurtkasi',
		code: 'SK456',
		remaining: 20,
		price: 80,
		rating: 4.0,
		reviews: 70,
		category: 'Sport anjomlari',
	},
	{
		name: 'Roman',
		code: 'R567',
		remaining: 200,
		price: 15,
		rating: 4.7,
		reviews: 150,
		category: 'Kitoblar',
	},
	{
		name: 'Pushti o‘yinchoq',
		code: 'P678',
		remaining: 500,
		price: 10,
		rating: 4.3,
		reviews: 80,
		category: 'Oyinchoqlar',
	},
]
